base_images:
  ansible:
    name: "4.13"
    namespace: ocp
    tag: ansible
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.13"
    namespace: ocp
    tag: openstack-installer
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.14"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.13"
  tools:
    name: "4.13"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.13"
    namespace: ocp
    tag: upi-installer
  verification-tests:
    name: verification-tests
    namespace: ci
    tag: latest
  vsphere-ci-python:
    name: vsphere-python
    namespace: ci
    tag: latest
releases:
  latest:
    prerelease:
      architecture: amd64
      product: ocp
      version_bounds:
        lower: 4.13.0-0
        upper: 4.14.0-0
  target:
    prerelease:
      architecture: amd64
      product: ocp
      version_bounds:
        lower: 4.14.0-0
        upper: 4.15.0-0
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: aws-c2s-ipi-disc-priv-fips-f28
  cron: 55 6 8 * *
  steps:
    cluster_profile: aws-c2s-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: openshift-upgrade-qe-sanity-disconnected
    workflow: cucushift-installer-rehearse-aws-c2s-ipi-disconnected-private
- as: aws-ipi-disc-priv-localzone-fips-f28
  cron: 6 2 6 * *
  steps:
    cluster_profile: aws-1-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      EXTRACT_MANIFEST_INCLUDED: "true"
      FIPS_ENABLED: "true"
    test:
    - chain: openshift-upgrade-qe-test-disconnected
    workflow: cucushift-installer-rehearse-aws-ipi-disconnected-private-edge-zone
- as: aws-ipi-disc-priv-sts-ep-fips-f28
  cron: 16 8 7 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      ENABLE_OTA_TEST: OCP-30832
      FIPS_ENABLED: "true"
    test:
    - chain: openshift-upgrade-qe-sanity-disconnected
    workflow: cucushift-installer-rehearse-aws-ipi-disconnected-private-cco-manual-security-token-service-private-s3-with-ep-sts-ec2-elb
- as: aws-ipi-shared-vpc-phz-sts-fips-f28
  cron: 42 19 6 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      EXTRACT_MANIFEST_INCLUDED: "true"
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-ipi-shared-vpc-phz-sts
- as: aws-ipi-usertags-custom-sg-fips-f28
  cron: 59 21 27 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-ipi-usertags-custom-security-groups
- as: aws-usgov-ipi-private-sts-f28
  cron: 3 21 21 * *
  steps:
    cluster_profile: aws-usgov-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      EXTRACT_MANIFEST_INCLUDED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-aws-usgov-ipi-private-cco-manual-security-token-service
- as: azure-ipi-disc-fullyprivate-f28
  cron: 0 15 21 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      ENABLE_OTA_TEST: OCP-27986
    test:
    - chain: openshift-upgrade-qe-sanity-disconnected
    workflow: cucushift-installer-rehearse-azure-ipi-disconnected-fullyprivate
- as: azure-mag-ipi-fips-f28
  cron: 11 14 27 * *
  steps:
    cluster_profile: azuremag-qe
    env:
      BASE_DOMAIN: qemag.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-azure-mag-ipi
- as: azure-stack-ipi-proxy-fips-f28
  cluster: build01
  cron: 3 4 5 * *
  steps:
    cluster_profile: azurestack-qe
    env:
      EXTRACT_MANIFEST_INCLUDED: "true"
      FIPS_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-azure-stack-ipi-proxy
- as: gcp-ipi-proxy-private-f28
  cron: 32 18 13 * *
  steps:
    cluster_profile: gcp-qe
    env:
      ENABLE_OTA_TEST: OCP-24358
    test:
    - chain: openshift-upgrade-qe-sanity
    workflow: cucushift-installer-rehearse-gcp-ipi-proxy-private
- as: ibmcloud-ipi-private-fips-f28
  cron: 52 11 23 * *
  steps:
    cluster_profile: ibmcloud-qe
    env:
      FIPS_ENABLED: "true"
    test:
    - chain: openshift-upgrade-qe-sanity
    workflow: cucushift-installer-rehearse-ibmcloud-ipi-private
- as: ibmcloud-ipi-proxy-private-rt-f28
  cron: 36 23 7 * *
  steps:
    cluster_profile: ibmcloud-qe
    env:
      RT_ENABLED: "true"
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-ibmcloud-ipi-proxy-private
- as: nutanix-ipi-proxy-fips-f28
  cluster: build01
  cron: 33 3 28 * *
  steps:
    cluster_profile: nutanix-qe-dis
    env:
      ENABLE_OTA_TEST: OCP-24358
      FIPS_ENABLED: "true"
    test:
    - ref: nutanix-upgrade-pre-config
    - chain: openshift-upgrade-qe-sanity
    workflow: cucushift-installer-rehearse-nutanix-ipi-proxy
- as: vsphere-ipi-disc-f28
  cron: 12 15 10 * *
  steps:
    cluster_profile: vsphere-dis-2
    env:
      ENABLE_OTA_TEST: OCP-30832
    leases:
    - env: VSPHERE_BASTION_LEASED_RESOURCE
      resource_type: vsphere-connected-2-quota-slice
    test:
    - chain: openshift-upgrade-qe-sanity-disconnected
    workflow: cucushift-installer-rehearse-vsphere-ipi-disconnected
- as: vsphere-ipi-ovn-dualstack-f28
  cron: 38 12 18 * *
  steps:
    cluster_profile: vsphere-elastic
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-vsphere-ipi-ovn-dualstack
- as: vsphere-ipi-proxy-fips-f28
  cron: 4 23 23 * *
  steps:
    cluster_profile: vsphere-dis-2
    env:
      ENABLE_OTA_TEST: OCP-24358
      FIPS_ENABLED: "true"
    leases:
    - env: VSPHERE_BASTION_LEASED_RESOURCE
      resource_type: vsphere-connected-2-quota-slice
    test:
    - chain: openshift-upgrade-qe-sanity
    workflow: cucushift-installer-rehearse-vsphere-ipi-proxy
zz_generated_metadata:
  branch: release-4.14
  org: openshift
  repo: openshift-tests-private
  variant: amd64-stable-4.14-upgrade-from-stable-4.13
