base_images:
  ansible:
    name: "4.13"
    namespace: ocp
    tag: ansible
  aws-efs-csi-operator-create-efs:
    name: "4.13"
    namespace: ocp
    tag: aws-efs-csi-operator-create-efs
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.13"
    namespace: ocp
    tag: openstack-installer
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.14"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.13"
  tools:
    name: "4.13"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.13"
    namespace: ocp
    tag: upi-installer
  verification-tests:
    name: verification-tests
    namespace: ci
    tag: latest
releases:
  latest:
    prerelease:
      architecture: multi
      product: ocp
      version_bounds:
        lower: 4.13.0-0
        upper: 4.14.0-0
  target:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: aws-ipi-byo-iam-role-efs-fips-amd-f28
  cron: 34 5 1 * *
  steps:
    cluster_profile: aws-qe
    dependency_overrides:
      OO_INDEX: quay.io/openshift-qe-optional-operators/aosqe-index:v4.13
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-byo-iam-role-efs
- as: aws-ipi-byo-kms-etcd-encryption-arm-f28
  cron: 2 18 2 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-aws-ipi-byo-kms-etcd-encryption
- as: aws-ipi-byo-kms-etcd-encryption-fips-amd-f28
  cron: 31 9 1 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-byo-kms-etcd-encryption
- as: aws-ipi-byo-route53-compact-cloudfront-arm-f28
  cron: 25 22 6 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
      SIZE_VARIANT: compact
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-byo-route53-registry-s3-cloudfront
- as: aws-ipi-imdsv2-arm-f28
  cron: 3 10 9 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-aws-ipi-imdsv2
- as: aws-ipi-imdsv2-fips-amd-f28
  cron: 15 14 17 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-imdsv2
- as: aws-ipi-ingress-lbtype-classic-arm-f28
  cron: 55 7 24 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-aws-ipi-ingress-lbtype-classic
- as: aws-ipi-ingress-lbtype-nlb-arm-f28
  cron: 22 18 13 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-ingress-lbtype-nlb
- as: aws-ipi-mini-perm-arm-f28
  cron: 54 19 15 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-aws-ipi-minimal-permission
- as: aws-ipi-ovn-ipsec-arm-mixarch-f28
  cron: 1 17 21 * *
  steps:
    cluster_profile: aws-qe
    env:
      ADDITIONAL_WORKER_ARCHITECTURE: x86_64
      ADDITIONAL_WORKER_VM_TYPE: m6i.xlarge
      ADDITIONAL_WORKERS: "1"
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "2"
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
      UPGRADE_CHECK_RUN_TAGS: '@heterogeneous'
      UPGRADE_PRE_RUN_TAGS: '@heterogeneous'
    test:
    - ref: ipi-install-heterogeneous
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-ovn-ipsec
- as: aws-ipi-ovn-ipsec-arm-mixarch-day2-f28
  cron: 3 12 13 * *
  steps:
    cluster_profile: aws-qe
    env:
      ADDITIONAL_WORKER_ARCHITECTURE: x86_64
      ADDITIONAL_WORKER_VM_TYPE: m6i.xlarge
      ADDITIONAL_WORKERS: "1"
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "2"
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
      UPGRADE_CHECK_RUN_TAGS: '@heterogeneous'
      UPGRADE_PRE_RUN_TAGS: '@heterogeneous'
    test:
    - chain: openshift-upgrade-qe-test-heterogeneous
    workflow: cucushift-installer-rehearse-aws-ipi-ovn-ipsec
- as: aws-ipi-proxy-sts-arm-f28
  cron: 50 8 11 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-proxy-cco-manual-security-token-service
- as: aws-ipi-sdn-arm-f28
  cron: 4 9 3 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-aws-ipi-sdn
- as: aws-ipi-sno-etcd-encryption-basecap-none-arm-f28
  cron: 6 20 19 * *
  steps:
    cluster_profile: aws-qe
    env:
      ADDITIONAL_ENABLED_CAPABILITIES: MachineAPI
      BASE_DOMAIN: qe.devcluster.openshift.com
      BASELINE_CAPABILITY_SET: None
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.2xlarge
      OCP_ARCH: arm64
      PERSISTENT_MONITORING: "false"
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-aws-ipi-sno-etcd-encryption
- as: aws-ipi-usertags-custom-sg-arm-f28
  cron: 34 5 15 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-aws-ipi-usertags-custom-security-groups
- as: aws-ipi-usertags-fips-amd-f28
  cron: 41 3 13 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      ENABLE_OTA_TEST: OCP-21588
      FIPS_ENABLED: "true"
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-usertags
- as: aws-upi-basecap-none-amd-f28
  cron: 11 5 3 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      BASELINE_CAPABILITY_SET: None
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-upi
- as: aws-upi-basecap-none-arm-f28
  cron: 1 23 28 * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      BASELINE_CAPABILITY_SET: None
      BOOTSTRAP_INSTANCE_TYPE: m6g.large
      MASTER_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
      PERSISTENT_MONITORING: "false"
      WORKER_INSTANCE_TYPE: m6g.xlarge
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-aws-upi
- as: azure-ipi-arm-mixarch-f28
  cron: 0 1 25 * *
  steps:
    cluster_profile: azure-qe
    env:
      ADDITIONAL_WORKER_ARCHITECTURE: x86_64
      ADDITIONAL_WORKER_VM_TYPE: Standard_D4s_v3
      ADDITIONAL_WORKERS: "1"
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "2"
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      OCP_ARCH: arm64
    test:
    - ref: ipi-install-heterogeneous
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-ipi
- as: azure-ipi-basecap-vset-additionalcap-arm-f28
  cron: 14 5 22 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      OCP_ARCH: arm64
      PERSISTENT_MONITORING: "false"
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-ipi-capability-baselinecaps-vset-additionalcaps
- as: azure-ipi-basecap-vset-arm-f28
  cron: 59 22 13 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      OCP_ARCH: arm64
      PERSISTENT_MONITORING: "false"
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-ipi-capability-baselinecaps-vset
- as: azure-ipi-des-fips-amd-f28
  cron: 31 8 2 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      ENABLE_DES_DEFAULT_MACHINE: "true"
      FIPS_ENABLED: "true"
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-ipi-disk-encryption-set
- as: azure-ipi-fullyprivate-proxy-arm-f28
  cron: 19 22 23 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      OCP_ARCH: arm64
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-ipi-fullyprivate-proxy
- as: azure-ipi-ingress-controller-arm-mixarch-f28
  cron: 59 13 23 * *
  steps:
    cluster_profile: azure-qe
    env:
      ADDITIONAL_WORKER_ARCHITECTURE: x86_64
      ADDITIONAL_WORKER_VM_TYPE: Standard_D4s_v3
      ADDITIONAL_WORKERS: "1"
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "2"
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      OCP_ARCH: arm64
    test:
    - ref: ipi-install-heterogeneous
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-ipi-ingress-custom-controller
- as: azure-ipi-ingress-custom-controller-fips-amd-f28
  cron: 11 6 5 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      FIPS_ENABLED: "true"
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-ipi-ingress-custom-controller
- as: azure-ipi-mini-perm-arm-f28
  cron: 20 14 22 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      OCP_ARCH: arm64
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-ipi-minimal-permission
- as: azure-ipi-oidc-mini-perm-arm-f28
  cron: 11 1 11 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      EXTRACT_MANIFEST_INCLUDED: "true"
      OCP_ARCH: arm64
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-ipi-cco-manual-workload-identity-minimal-permission
- as: azure-ipi-ovn-etcd-encryption-compact-arm-f28
  cron: 15 4 9 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      OCP_ARCH: arm64
      SIZE_VARIANT: compact
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-ipi-ovn-etcd-encryption
- as: azure-ipi-ovn-ipsec-arm-mixarch-day2-f28
  cron: 36 11 22 * *
  steps:
    cluster_profile: azure-qe
    env:
      ADDITIONAL_WORKER_ARCHITECTURE: x86_64
      ADDITIONAL_WORKER_VM_TYPE: Standard_D4s_v3
      ADDITIONAL_WORKERS: "1"
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "2"
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      OCP_ARCH: arm64
      UPGRADE_CHECK_RUN_TAGS: '@heterogeneous'
      UPGRADE_PRE_RUN_TAGS: '@heterogeneous'
    test:
    - chain: openshift-upgrade-qe-test-heterogeneous
    workflow: cucushift-installer-rehearse-azure-ipi-ovn-ipsec
- as: azure-ipi-ovn-ipsec-azurefile-csi-arm-f28
  cron: 57 12 13 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      OCP_ARCH: arm64
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-ipi-ovn-ipsec-azurefile-csi
- as: azure-ipi-private-spec-net-type-spec-perm-arm-f28
  cron: 46 16 6 * *
  steps:
    cluster_profile: azure-qe
    env:
      AZURE_COMPUTE_NETWORKING_TYPE: Basic
      AZURE_DEFAULT_MACHINE_NETWORKING_TYPE: Accelerated
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      CONTROL_PLANE_INSTANCE_TYPE: Standard_D8ps_v5
      OCP_ARCH: arm64
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-ipi-private-networking-type-minimal-permission
- as: azure-ipi-sdn-arm-f28
  cron: 25 8 7 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      OCP_ARCH: arm64
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-ipi-sdn
- as: azure-ipi-sno-etcd-encryption-arm-f28
  cron: 27 6 17 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      OCP_ARCH: arm64
      SINGLE_NODE_AZURE_INSTANCE_TYPE: Standard_D32ps_v5
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-ipi-sno-etcd-encryption
- as: azure-ipi-ultrassd-disks-arm-f28
  cron: 21 4 14 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      OCP_ARCH: arm64
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-ipi-ultrassd-disk
- as: azure-ipi-ultrassd-disks-fips-amd-f28
  cron: 37 18 15 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      ENABLE_OTA_TEST: OCP-21588
      FIPS_ENABLED: "true"
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-ipi-ultrassd-disk
- as: azure-ipi-usertags-arm-f28
  cron: 43 10 5 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      OCP_ARCH: arm64
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-ipi-usertags
- as: azure-upi-arm-f28
  cron: 34 0 8 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      BOOTSTRAP_NODE_TYPE: Standard_D4ps_v5
      COMPUTE_NODE_TYPE: Standard_D4ps_v5
      CONTROL_PLANE_NODE_TYPE: Standard_D8ps_v5
      OCP_ARCH: arm64
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-azure-upi
zz_generated_metadata:
  branch: release-4.14
  org: openshift
  repo: openshift-tests-private
  variant: multi-nightly-4.14-upgrade-from-stable-4.13
